In [4]:
import numpy as np


In [6]:
negative_array = np.array([-1, -5, -10, -20, -3])

absolute_array = np.abs(negative_array)
print("Original array:", negative_array)
print("Absolute values:", absolute_array)

Original array: [ -1  -5 -10 -20  -3]
Absolute values: [ 1  5 10 20  3]


In [10]:
float_array = np.array([1.2, 3.8, -4.5, 7.6, -2.3])
rounded_array = np.rint(float_array)

print("Original array:", float_array)
print("Rounded array:", rounded_array)

Original array: [ 1.2  3.8 -4.5  7.6 -2.3]
Rounded array: [ 1.  4. -4.  8. -2.]


In [12]:
matrix = np.arange(2, 11).reshape(3, 3)

print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [32]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

reshaped_array = array.reshape(3, 3)
df = pd.DataFrame(reshaped_array, columns=['A', 'B', 'C'])
print(df)


   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [20]:
#OR below in simple way same as above

#1
import numpy as np
a=np.array([-1,-2,-3])
a
np.absolute(a)



array([1, 2, 3])

In [22]:
#2
b=np.array([1.2,2.4,3.5,4.6,5.9,6.0])
np.round(b)

array([1., 2., 4., 5., 6., 6.])

In [24]:
#3
c=np.arange(2,11)
print(c)
c.reshape(3,3)

[ 2  3  4  5  6  7  8  9 10]


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [26]:
import pandas as pd
d=[1,2,3,4,5]
print(d)
e=pd.Series(d)
print(e)
f=np.array([1,2,3,4,5])
print(f)
g=pd.Series(f)
print(g)

[1, 2, 3, 4, 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64
[1 2 3 4 5]
0    1
1    2
2    3
3    4
4    5
dtype: int32


In [28]:
h={'a':1,'b':2,'c':3}
h

{'a': 1, 'b': 2, 'c': 3}

In [30]:
#5
j=np.array([10,20,30,40])
k=pd.DataFrame(j)
k

0
0  10
1  20
2  30
3  40