In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv('Football_dataset.csv')
df.head()

Team      Tournament  Goals Scored  Shots pg  Yellow Cards  \
0      Manchester City  Premier League            83      15.8            46   
1        Bayern Munich      Bundesliga            99      17.1            44   
2  Paris Saint-Germain         Ligue 1            86      15.0            73   
3            Barcelona          LaLiga            85      15.3            68   
4          Real Madrid          LaLiga            67      14.4            57   

   Red Cards  Shooting Accuracy  AerialsWon  Rating  Discipline  Own Fouls  \
0          2               89.4        12.8    7.01          48          1   
1          3               85.5        12.9    6.95          47          2   
2          7               89.5         9.5    6.88          80          3   
3          2               89.7        10.6    6.87          70          4   
4          2               87.7        11.8    6.86          59          5   

   Opponent Fouls  
0               1  
1               2  
2               3  
3               5  
4               6

In [5]:
df.tail()

Team      Tournament  Goals Scored  Shots pg  Yellow Cards  \
24              Everton  Premier League            47      10.5            59   
25     Bayer Leverkusen      Bundesliga            53      13.0            58   
26  Eintracht Frankfurt      Bundesliga            69      13.2            80   
27               Monaco         Ligue 1            76      12.8            74   
28                 Roma         Serie A            68      14.3            84   

    Red Cards  Shooting Accuracy  AerialsWon  Rating  Discipline  Own Fouls  \
24          2               81.4        17.7    6.73          61          1   
25          0               84.4        13.1    6.73          58          2   
26          1               79.6        17.9    6.73          81          3   
27          7               82.7        16.5    6.73          81          4   
28          3               84.5        12.1    6.71          87          5   

    Opponent Fouls  
24               1  
25               2  
26               3  
27               5  
28               6

a)how many teams participated in this tournment

In [3]:
teams_participated = df['Team'].nunique()
print(f"The nmber pf teams participated in this tournment : {teams_participated}")

The nmber pf teams participated in this tournment : 29


In [4]:
df.isnull().sum().any()

False

b)list top two teams with high discipline and bottom two teams with low disciplines(you can consider red and yellow cards to calculate discipline.)

In [8]:

top_teams=df.groupby('Team')['Discipline'].sum().nlargest(2)
print("Top two teams with highest discipline:")
print(top_teams)

Top two teams with highest discipline:
Team
Atletico Madrid    100
Roma                87
Name: Discipline, dtype: int64


In [9]:
bottom_teams=df.groupby('Team')['Discipline'].sum().nsmallest(2)
print("Bottom two teams with lowest discipline:")
print(bottom_teams)

Bottom two teams with lowest discipline:
Team
Liverpool            40
Borussia Dortmund    44
Name: Discipline, dtype: int64


c)on average how many yellow cards are given per team

In [10]:
average_yellow=df.groupby('Team')['Yellow Cards'].mean()
overall_average=average_yellow.mean()
print(f"on average, {overall_average:2f} yellpow cards are given per team.")

on average, 62.655172 yellpow cards are given per team.


d)how many teams scored more than 5 goals and which are those teams

In [16]:
teams_goals=df[df['Goals Scored']>5]
num_teams_morethan_5goals=teams_goals['Team'].nunique()
# print(f"{num_teams_morethan_5goals} teams scored more than 5 goals.")
# print("\n The teams that scored more than 5 goals are:")
print(teams_goals[['Team','Goals Scored']])

                   Team  Goals Scored
0       Manchester City            83
1         Bayern Munich            99
2   Paris Saint-Germain            86
3             Barcelona            85
4           Real Madrid            67
5     Manchester United            73
6              Juventus            77
7           Aston Villa            55
8     Borussia Dortmund            75
9       Atletico Madrid            67
10             Atalanta            90
11              Chelsea            58
12            Liverpool            68
13             AC Milan            74
14                Lille            64
15            Tottenham            68
16               Napoli            86
17            Leicester            68
18            Wolfsburg            61
19                Inter            89
20                 Lyon            81
21           RB Leipzig            60
22                Leeds            62
23             West Ham            62
24              Everton            47
25     Bayer

e)which team is most accurate in shooting

In [18]:
most_accurate_team=df.loc[df['Shooting Accuracy'].idxmax()]
print(f"the most accurate team in shooting is: {most_accurate_team['Team']}"
f"with a shooting accuracy of {most_accurate_team['Shooting Accuracy']}.")
sorted_teams_by_accuracy=df.sort_values(by='Shooting Accuracy',ascending=False)
print("\n Teams sorted by shooting accuracy:")
print(sorted_teams_by_accuracy[['Team','Shooting Accuracy']])

the most accurate team in shooting is: Barcelonawith a shooting accuracy of 89.7.

 Teams sorted by shooting accuracy:
                   Team  Shooting Accuracy
3             Barcelona               89.7
2   Paris Saint-Germain               89.5
0       Manchester City               89.4
6              Juventus               88.3
4           Real Madrid               87.7
19                Inter               87.0
16               Napoli               87.0
11              Chelsea               87.0
12            Liverpool               85.7
1         Bayern Munich               85.5
8     Borussia Dortmund               85.5
5     Manchester United               84.8
20                 Lyon               84.7
28                 Roma               84.5
25     Bayer Leverkusen               84.4
13             AC Milan               84.0
10             Atalanta               83.5
14                Lille               83.5
21           RB Leipzig               83.2
9       Atletico Madr

F)How many teams made more fouls than their opponents?

In [25]:
import pandas as pd
fouls=df[df['Own Fouls'] >df['Opponent Fouls']]
more_Fouls=fouls['Team'].unique()
print(more_Fouls)
print(fouls[['Team','Own Fouls','Opponent Fouls']])

['Juventus' 'Aston Villa' 'Liverpool' 'AC Milan' 'Lille' 'Tottenham'
 'Wolfsburg' 'Inter' 'Lyon' 'RB Leipzig' 'Leeds' 'West Ham']
           Team  Own Fouls  Opponent Fouls
6      Juventus          7               1
7   Aston Villa          8               2
12    Liverpool          5               1
13     AC Milan          6               2
14        Lille          7               3
15    Tottenham          8               5
18    Wolfsburg          3               1
19        Inter          4               2
20         Lyon          5               3
21   RB Leipzig          6               5
22        Leeds          7               6
23     West Ham          8               7


In [29]:
import math
#chech wheather some values are NaN or not
print(math.isnan(56))
print(math.isnan(-45.34))
print(math.isnan(+45.34))
print(math.isnan(math.inf))
print(math.isnan(float("nan")))
print(math.isnan(float("inf")))
print(math.isnan(float("-inf")))
print(math.isnan(math.nan))









False
False
False
False
True
False
False
True


In [7]:
import numpy
x=numpy.array([[1,2,3],[4,5,6],[7,8,9]])
print(x.ndim)
print(x.shape)
print(x.size)


2
(3, 3)
9


In [35]:
a=numpy.array([20,30,40,50,60])
b=numpy.arange(5)
c=a-b
c

array([20, 29, 38, 47, 56])

In [43]:
a=numpy.array([[1,2],[3,4],[5,6],[7,8]])
print(a.ndim)
print(a.shape)
print(a.size)

2
(4, 2)
8


In [9]:
a=numpy.array([20,30,40,50,60])
b=numpy.arange(5)
c=a-b
c

array([20, 29, 38, 47, 56])

In [47]:
x=numpy.array([1,2,3,4,5])
avg=x.mean()
sum=x.sum()
sx=numpy.sin(x)
sx

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])