In [7]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

# Training data (Weight, Size) and labels
X_train = np.array([[150, 7], [160, 8], [140, 6], [300, 12], [310, 13], [290, 11]])
y_train = np.array(['Apple', 'Apple', 'Apple', 'Orange', 'Orange', 'Orange'])

# New fruit to classify
X_test = np.array([[155, 7.5]])

# KNN model with K=3
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# Predict the fruit type
prediction = knn.predict(X_test)
print("Predicted fruit:", prediction[0])


Predicted fruit: Apple


In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

# Load the dataset
df = pd.read_csv("iris_data.csv")

# Features and target variable
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
Y = df['species']

# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# KNN model with K=5
k = 5
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, Y_train)

# Predict the species
Y_pred = knn.predict(X_test)

# Calculate accuracy and confusion matrix
print("Accuracy:", accuracy_score(Y_test, Y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(Y_test, Y_pred))


Accuracy: 1.0

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
