In [ ]:
#mathematical function:



In [ ]:
import numpy as np

In [4]:
a1=np.array([2,3,4])
a2=np.array([5,6,1])


In [5]:
np.sum(a1)

9

In [6]:
np.sum(a2)

12

In [10]:
np.sum([a1,a2],axis=0)


array([7, 9, 5])

In [11]:
np.sum([a1,a2],axis=1)

array([ 9, 12])

In [14]:
np.subtract(a1,a2)

array([-3, -3,  3])

In [15]:
np.multiply(a1,a2)

array([10, 18,  4])

In [16]:
np.divide(a1,a2)

array([0.4, 0.5, 4. ])

In [ ]:
#additional function

#arrange

In [20]:
import numpy as np

np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
#np.arange(start,end+1,step+1)

In [24]:
a1=np.arange(1,11,3)
a1

array([ 1,  4,  7, 10])