In [5]:
import numpy as np

In [62]:
# 1D Array
# Syntax: np.array([values])
a1 = np.array([1,2,3,4,5])
a1


array([1, 2, 3, 4, 5])

In [60]:
a2=np.array([1.1,2.2,3.3,4.4,5.5])
a2
print(type(a1))

<class 'numpy.ndarray'>


In [58]:
a3=np.array([1,2,3.3])  #numpy automaticaly typecast here
a3

array([1. , 2. , 3.3])

In [27]:
a4=np.array([1,2,3,4, "hi"])
a4

array(['1', '2', '3', '4', 'hi'], dtype='<U11')

In [35]:
a5=np.array([1,2,3.3], 'int')
a5

array([1, 2, 3])

In [37]:
a6=np.array([1,2,3.3], 'float')
a6

array([1. , 2. , 3.3])

In [7]:
a1=np.arange(1,11,3)
a1

array([ 1,  4,  7, 10])

In [48]:
#create a list and and print it in array
a=[1,2,3,4,55,5,]
aa=np.arrey(a)
a

AttributeError: module 'numpy' has no attribute 'arrey'

In [52]:
# array operation
#ndim
a1.ndim

1

In [66]:
# size 
#a1 =np.array([1,2,3,4,5])
#a1
a1.size

5

In [70]:
a1 =np.array([1,2,3,4,5])
a1
a1.dtype

dtype('int32')

In [74]:
# shape
a1.shape

(5,)

In [76]:
# 2D Array
# syntax: np.array([[]])

In [80]:
a5=np.array([[1,2,3,4]])
a5

array([[1, 2, 3, 4]])

In [84]:
a5.ndim #its 2D array

2

In [146]:
a6=np.array([[1,2,3,3,3],[4,5,6,6,6],[7,8,9,9,7]])
a6

array([[1, 2, 3, 3, 3],
       [4, 5, 6, 6, 6],
       [7, 8, 9, 9, 7]])

In [92]:
a6.ndim

2

In [130]:
a7=np.array([[1,2,3,3,3],[4,5,6,6,6],[7,8,9,9,7],[2,5,9,0,1.3]])
a7

array([[1. , 2. , 3. , 3. , 3. ],
       [4. , 5. , 6. , 6. , 6. ],
       [7. , 8. , 9. , 9. , 7. ],
       [2. , 5. , 9. , 0. , 1.3]])

In [134]:
a7.size

20

In [138]:
a7.shape

(4, 5)

In [148]:
a7.ndim

2

In [154]:
# Array Function
# Syntax: np.zeros((shape))


In [162]:
a8=np.zeros((3,3))
a8

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [172]:
a8=np.zeros((3,3),'int'),
a8

(array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]),)

In [194]:
a9=np.ones((3,3),'int'),
a9

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),)

In [206]:
# np.full((3,2),5)
s1= np.full((3,3),5)
s1

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])