In [9]:
# SVM implementation in Python
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split 
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.svm import SVC 
from sklearn.metrics import accuracy_score 

# Sample dataset: Emails and their labels
data = {
    "email": [
        "Win a free lottery now",
        "Important meeting at 5 PM",
        "Congratulations! You won a prize",
        "Please review the attached report",
        "Claim your free gift today",
        "Your invoice is attached"],
    "label": [1, 0, 1, 0, 1, 0]  # 1 = Spam, 0 = Not Spam
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Convert text data to numerical form
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df["email"])

# Define labels
y = df["label"]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train SVM model
svm_model = SVC(kernel="linear")  # Linear SVM for classification
svm_model.fit(X_train, y_train)

# Predictions
y_pred = svm_model.predict(X_test)

# Model accuracy
accuracy = accuracy_score(y_test, y_pred)

print(f"Model Accuracy: {accuracy * 100:.2f}%")

# Test with a new email
new_email = ["Congratulations! You won"]
new_email_vectorized = vectorizer.transform(new_email)

prediction = svm_model.predict(new_email_vectorized)

print("Spam" if prediction[0] == 1 else "Not Spam")


Model Accuracy: 50.00%
Spam


In [11]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# Load the dataset
df = pd.read_csv("iris_data.csv")

# Define features (X) and target (Y)
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
Y = df['species']

# Split dataset into training and testing sets (80% train, 20% test)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Train SVM model with a linear kernel
svm_model = SVC(kernel='linear')
svm_model.fit(X_train, Y_train)

# Make predictions
Y_pred = svm_model.predict(X_test)

# Print model accuracy
print("Accuracy:", accuracy_score(Y_test, Y_pred))

# Print confusion matrix
print("\nConfusion Matrix:\n", confusion_matrix(Y_test, Y_pred))


Accuracy: 1.0

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
